### ISSUE TITLE
Tox option to enable and disable the option

### ISSUE THREAD

**Issue by tibortakacs** [djpugh/azure_devops_artifacts_helpers#66]
The current implementation installs the `artifacts-keyring` package in all `tox` environments if this package is available. In some cases, this could be undesired, and more control would be beneficial. For example, adding the `artifacts_keyring = True/False` tox config and `--with-artifacts-keyring` option would be a potential solution to gain more control.

@djpugh Would you consider this as a potential feature in the library? This could be a non-backward-compatible change. Would this be an option with a major version bump?

**Comment by djpugh** [comment]
Its a good idea - I think this could be made backwards compatible (ie default to installing) based on some very quick thoughts, especially for tox v4 - v3 might be a bit more complex because of how hooks were handled there.

I'm travelling next week, but may be able to have a look the week after, and see if this can be done!

**Comment by djpugh** [comment]
It looks pretty easy to add config files/options to the tox v4 config and use them - I've put together a working example for it in config - is the cli config likely to be used (I rarely use tox cli options in how I use it)

**Comment by tibortakacs** [comment]
Thank you, @djpugh . In my custom `tox` extension, I have the `disable-....` CLI option to overwrite the `tox.ini` config. I found this useful to disable `artifacts-keyring` without modifying the `tox.ini` config itself. This might be a good use case for this library.
