### ISSUE TITLE
How to setup with Poetry

### ISSUE THREAD

**Issue by mpicard** [djpugh/azure_devops_artifacts_helpers#67]
Hi how does one set this up for poetry? Can someone provide documentation/example please?

**Comment by djpugh** [comment]
I haven't tried it with poetry before, but it could be possible through ``virtualenvs.options`` in the poetry config (see https://python-poetry.org/docs/configuration/) - I'll try to put together a test case for this and docs - although diving a bit deeper it might not be - worst case scenario now is to create a virtualenv directly using the virtualenv approach and then take over it with poetry.

**Comment by djpugh** [comment]
Looks like it isn't processed due to https://github.com/python-poetry/poetry/blob/c4c857e917c863bff9e97371c7dff45b704f6140/src/poetry/utils/env.py#L1119

Suggested work around is to create a vanilla virtualenv and then use poetry from there (see the docs at https://djpugh.github.io/azure_devops_artifacts_helpers/usage.html) - if that works for you, I'll add a specific section for poetry

**Comment by djpugh** [comment]
You should also be able to use the environment variable
```
VIRTUALENV_SEEDER=azdo-pip
```

It should be possible to create a poetry plugin for this if that is helpful - please let me know and I can have a go!

**Comment by djpugh** [comment]
I just tested this approach, and I've added this comment to [usage.rst](https://github.com/djpugh/azure_devops_artifacts_helpers/blob/bfa6cec6851ca6e75ac22dac9abd3b9618559752/docs/source/usage.rst?plain=1#L30)
